blank_issues_enabled: false
contact_links:
  - name: GitHub Q&A
    url: https://github.com/aamirazad/terranaut/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: GitHub Feature Requests
    url: https://github.com/aamirazad/terranaut/discussions/new?category=feature-requests
    about: Propose new functionality here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/aamirazad/terranaut/security/policy
    about: Please report security vulnerabilities here.
